# numpy Highlight

- toc: true
- branch: master
- badges: true
- comments: true
- author: Kim Jeewoo
- categories: [Python, Python Tutorial]
- image: images/numpy_logo.png

# Reference

ref. https://numpy.org/doc/stable/user/index.html#

ref. https://github.com/guebin/IP2022

# NumPy

- Numerical Python

# Import

In [2]:
import numpy as np

# Array Creation(ndarray)

- N Dimensional Array

In [3]:
A = np.array([1,2,3])
A

array([1, 2, 3])

In [4]:
mylist = [3, 4, 5]
array_from_list = np.array(mylist)
array_from_list

array([3, 4, 5])

In [5]:
mytuple = (4,5,6)
array_from_tuple = np.array(mytuple)
array_from_tuple

array([4, 5, 6])

In [6]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.linspace(0,1,12) # 0 ~ 1을 12등분하여 만듬 (끝점을 포함)

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091, 1.        ])

In [8]:
len(np.linspace(0,1,12))

12

In [9]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [10]:
np.arange(1,6)

array([1, 2, 3, 4, 5])

In [11]:
np.zeros(3) # 0을 3개

array([0., 0., 0.])

In [12]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.ones(3) # 1을 3개

array([1., 1., 1.])

In [14]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.eye(3) # 단위 행렬

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
np.diag([1,2,3]) # 대각선이 1,2,3인 행렬

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

# Broadcasting

In [17]:
A+1 # 덧셈

array([2, 3, 4])

In [18]:
A-4 # 뺄셈

array([-3, -2, -1])

In [19]:
A*2 # 곱셈

array([2, 4, 6])

In [20]:
A/2 # 나눗셈

array([0.5, 1. , 1.5])

In [21]:
A**2 # 제곱

array([1, 4, 9])

In [22]:
A%2 # 나머지

array([1, 0, 1], dtype=int32)

In [23]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [24]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [25]:
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [26]:
np.sin(A)

array([0.84147098, 0.90929743, 0.14112001])

In [27]:
A = np.array([11,22,33,44,55,66])

# Indexing

In [28]:
A[2]

33

In [29]:
A[5]

66

In [30]:
A[1:4]

array([22, 33, 44])

In [31]:
A[[0,2,4]]

array([11, 33, 55])

In [32]:
A[[True, False, True, False, False, True]]

array([11, 33, 66])

In [33]:
A < 33

array([ True,  True, False, False, False, False])

In [34]:
A[A<33]

array([11, 22])

## Matrix Indexing

In [35]:
A2 = np.array([[1,2,3,4],[-1,-2,-3,-4],[5,6,7,8],[-5,-6,-7,-8]])
A2

array([[ 1,  2,  3,  4],
       [-1, -2, -3, -4],
       [ 5,  6,  7,  8],
       [-5, -6, -7, -8]])

In [36]:
A2[1][3]

-4

In [37]:
A2[1,3]

-4

In [38]:
A2[0, 0:2]

array([1, 2])

In [39]:
A2[0]

array([1, 2, 3, 4])

In [40]:
A2[0, 2:]

array([3, 4])

In [41]:
A2[:, :]

array([[ 1,  2,  3,  4],
       [-1, -2, -3, -4],
       [ 5,  6,  7,  8],
       [-5, -6, -7, -8]])

In [42]:
A2[[0,2], :]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [43]:
A2[[0,2]]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

# Useful Functions

## np.random

```{python}
np.random.
```

### np.random.rand

```{python}
np.random.rand(N)
```

In [231]:
np.random.rand(10) # 0~1 사이에서 10개의 난수 생성

array([0.45750574, 0.26272651, 0.97333158, 0.838797  , 0.30833822,
       0.90005548, 0.15576246, 0.42542199, 0.36933063, 0.23212799])

In [230]:
np.random.rand(10)*2 # (0~1)*2 = 0~2 사이에서 10개의 난수 생성

array([0.12494504, 1.95142067, 1.53362653, 0.24277993, 0.29892386,
       0.17080696, 0.83316001, 1.82392447, 1.12983406, 1.70590512])

In [232]:
np.random.rand(10)+1 # 1~2 사이에서 10개의 난수 생성

array([1.75938504, 1.35689293, 1.28755874, 1.62206564, 1.82463073,
       1.45762159, 1.37307502, 1.96544966, 1.2656653 , 1.20280198])

In [233]:
np.random.rand(10)*2+1 # 1~3 사이에서 10개의 난수 생성

array([1.78153814, 2.00624373, 1.59890958, 1.00057509, 1.9755774 ,
       2.61476828, 2.99251409, 1.80493805, 1.66917611, 1.26220716])

### np.random.randn

```{python}
np.random.randn(N)
```

In [237]:
np.random.randn(10) # 표준정규분포에서 10개 추출

array([ 1.33180976,  0.17026483, -0.51419985, -1.27040806,  1.74260265,
       -0.3585314 , -0.1845767 ,  0.62244756,  0.45047948, -0.39841109])

In [240]:
np.random.randn(10)*2 # 평균이 0이고 표준편차가 2인 정규분포

array([-1.98634475,  1.45185424,  0.73185989,  0.68840108,  1.10816262,
        2.6173764 ,  0.81075249, -0.37013936,  2.11077527,  2.37402885])

In [241]:
np.random.randn(10)*2 + 3 # 평균이 0이고 표준편차가 3인 정규분포

array([ 2.49945435, -0.16090429,  3.2248306 , -1.7684026 ,  4.57076217,
        6.00691862,  1.91930938,  2.42286171,  4.30676521,  3.90826826])

### np.random.randint

- 중복을 허용하지 않고 정수를 생성한다.

In [250]:
np.random.randint(7) # [0,7)의 범위에서 정수 한 개 생성

0

In [259]:
np.random.randint(7, size = (20,)) 

array([0, 1, 6, 2, 4, 6, 3, 0, 1, 4, 0, 2, 2, 3, 3, 1, 3, 1, 4, 4])

In [253]:
np.random.randint(7, size = (2,2)) # [0,7)의 범위 무작위 정수가 원소인 2x2 행렬을 생성한다.

array([[5, 4],
       [1, 1]])

In [255]:
np.random.randint(low=10, high=20, size=(2,5)) # [10, 20)의 범위에서 정수 한 개 생성

array([[10, 15, 13, 18, 14],
       [19, 11, 19, 12, 17]])

> Warning : np.random.randint(high = N)은 사용할 수 없다.

### np.random.choice

- 복원추출이 default

In [261]:
np.random.choice(5,20)

array([0, 0, 4, 3, 3, 3, 4, 4, 4, 4, 3, 0, 2, 1, 2, 2, 2, 3, 4, 0])

In [263]:
np.random.choice(['apple', 'orange', 'banana'], 20)

array(['apple', 'orange', 'orange', 'orange', 'banana', 'banana',
       'banana', 'apple', 'banana', 'banana', 'apple', 'orange', 'banana',
       'orange', 'apple', 'orange', 'orange', 'orange', 'banana',
       'banana'], dtype='<U6')

In [266]:
np.random.choice(5, 2, replace = False) # Replace = False로 하면 비복원추출을 시행한다.

array([3, 0])

### np.random.binomial

In [267]:
np.random.binomial(n=10, p=0.2, size = (5,))

array([1, 2, 4, 3, 1])

### np.random.normal

```{python}
np.random.normal(loc = mean, scale = stdev, size)
default : np.random.normal(loc = 0, scale = 1, size = None)
```

In [242]:
np.random.normal(2, 3, 10) # 평균이 2이고 표준편차가 3인 정규분포

array([ 0.27916784,  4.09308918,  4.77967288,  6.62465688, -2.00309933,
        2.71028234, -1.82185251,  4.28805909,  9.35082561,  4.34941445])

### np.random.uniform

In [271]:
np.random.uniform(low=2, high=4, size = (5,)) # 균등분포

array([3.97150664, 2.10397129, 2.02828229, 2.1300076 , 2.739048  ])

In [270]:
np.random.poisson(lam=5, size=(5,))

array([8, 5, 6, 3, 7])

### np.random.poisson

In [272]:
np.random.poisson(lam=5, size=(5,))

array([1, 3, 6, 3, 5])

## .reshape

> Tip: R의 `dim` 함수와 유사하다.

In [44]:
A = np.array([11,22,33,44,55,66])
A

array([11, 22, 33, 44, 55, 66])

In [45]:
A.reshape(2,3)

array([[11, 22, 33],
       [44, 55, 66]])

In [46]:
A

array([11, 22, 33, 44, 55, 66])

In [47]:
A = A.reshape(2,3)
A

array([[11, 22, 33],
       [44, 55, 66]])

> note : reshape with `-1`

In [48]:
A = np.arange(24)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [49]:
A.reshape(2,-1) # 행의 수가 2인 행렬, 열은 알아서 맞춰

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [50]:
A.reshape(4, -1) # 행의 수가 4인 행렬, 열은 알아서 맞춰

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [51]:
A.reshape(-1, 4) # 열의 수가 4인 행렬, 행은 알아서 맞춰

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [52]:
A.reshape(-1) # 다시 길이가 24인 벡터로

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

## .shape

In [99]:
A = np.array(3.14) # Scalar, 0d array
A.shape

()

In [100]:
A = np.array([3.14]) # Vector, 1d array
A.shape

(1,)

In [102]:
A = np.array([[3.14]]) # Matrix, 2d array
A.shape

(1, 1)

In [103]:
A = np.array([[[3.14]]]) # Tensor, 3d array
A.shape

(1, 1, 1)

In [105]:
A = np.array([[1,2,3],[2,5,6],[4,4,2]])
A.shape

(3, 3)

## .T

In [65]:
A = np.arange(4).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [67]:
A.T # 전치행렬

array([[0, 2],
       [1, 3]])

## np.linalg.inv

In [70]:
np.linalg.inv(A) # 역행렬

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

## @

In [72]:
A @ np.linalg.inv(A)

array([[1., 0.],
       [0., 1.]])

## np.concatenate

In [107]:
A = np.array([1,2])
B = np.array([4,5])
np.concatenate([A, B])

array([1, 2, 4, 5])

In [112]:
A = np.arange(4).reshape(2,2)
B = np.arange(10,14).reshape(2,2)
np.concatenate([A, B]) # axis = 0이 생략되어 있다.

array([[ 0,  1],
       [ 2,  3],
       [10, 11],
       [12, 13]])

In [126]:
A=np.array(range(4)).reshape(2,2) 
B=np.array(range(2)).reshape(2,1)  
np.concatenate([a,b],axis=1) # 꼭 같은 차원일 필요는 없고, 붙여지는 부분의 길이만 같으면 됨

array([[0, 1, 0],
       [2, 3, 1]])

In [113]:
A = np.arange(4).reshape(2,2)
B = np.arange(10,14).reshape(2,2)
np.concatenate([A, B], axis=1)

array([[ 0,  1, 10, 11],
       [ 2,  3, 12, 13]])

In [120]:
# collapse-output
A = np.array(range(2*3*4)).reshape(2,3,4)
B = - A
A, B

(array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]),
 array([[[  0,  -1,  -2,  -3],
         [ -4,  -5,  -6,  -7],
         [ -8,  -9, -10, -11]],
 
        [[-12, -13, -14, -15],
         [-16, -17, -18, -19],
         [-20, -21, -22, -23]]]))

In [119]:
# collapse-output
np.concatenate([A,B], axis=0)

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23]],

       [[  0,  -1,  -2,  -3],
        [ -4,  -5,  -6,  -7],
        [ -8,  -9, -10, -11]],

       [[-12, -13, -14, -15],
        [-16, -17, -18, -19],
        [-20, -21, -22, -23]]])

In [121]:
# collapse-output
np.concatenate([A,B], axis=1)

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11],
        [  0,  -1,  -2,  -3],
        [ -4,  -5,  -6,  -7],
        [ -8,  -9, -10, -11]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23],
        [-12, -13, -14, -15],
        [-16, -17, -18, -19],
        [-20, -21, -22, -23]]])

In [122]:
# collapse-output
np.concatenate([A,B], axis=2)

array([[[  0,   1,   2,   3,   0,  -1,  -2,  -3],
        [  4,   5,   6,   7,  -4,  -5,  -6,  -7],
        [  8,   9,  10,  11,  -8,  -9, -10, -11]],

       [[ 12,  13,  14,  15, -12, -13, -14, -15],
        [ 16,  17,  18,  19, -16, -17, -18, -19],
        [ 20,  21,  22,  23, -20, -21, -22, -23]]])

## np.stack

> Warning : 

In [129]:
A = np.array([1,2,3])
B = np.array([2,3,4])
np.concatenate([A,B], axis = 1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [133]:
A = np.array([1,2,3])
B = np.array([2,3,4])
np.stack([A,B], axis=0)

array([[1, 2, 3],
       [2, 3, 4]])

In [138]:
np.stack([A,B], axis=1)

array([[1, 2],
       [2, 3],
       [3, 4]])

In [140]:
A = np.arange(3*4*5).reshape(3,4,5) 
B = - A

A.shape, B.shape

((3, 4, 5), (3, 4, 5))

In [ ]:
# collapse-output
np.stack([A,B], axis = 0)

In [160]:
np.stack([A,B], axis = 0).shape # axis = 0 <==> axis = -4

(2, 3, 4, 5)

In [161]:
np.stack([A,B], axis = 1).shape # axis = 1 <==> axis = -3

(3, 2, 4, 5)

In [162]:
np.stack([A,B], axis = 2).shape # axis = 2 <==> axis = -2

(3, 4, 2, 5)

In [163]:
np.stack([A,B], axis = 3).shape # axis = 3 <==> axis = -1

(3, 4, 5, 2)

### Difference between np.concatenate and np.stack

`np.concatenate`는 축의 총 개수를 유지하면서 결합한다.

`np.stack`은 축의 개수를 하나 증가시키면서 결합한다.

## np.diff

In [215]:
A = np.array([1,2,4,6,7])
np.diff(A)

array([1, 2, 2, 1])

In [216]:
np.diff(np.diff(A))

array([ 1,  0, -1])

In [224]:
np.diff(A, prepend=100) # np.diff(np.array([100] + A.tolist()) ), 즉 맨 앞에 100을 추가하여 차분

array([-99,   1,   2,   2,   1])

In [223]:
np.diff(A, append=100) # np.diff(np.array(A.tolist() + [100]) ), 즉 맨 뒤에 100을 추가하여 차분

array([ 1,  2,  2,  1, 93])

In [225]:
A = np.arange(24).reshape(4,6)
A

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [227]:
np.diff(A, axis = 0)

array([[6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6]])

In [273]:
np.diff(A, axis = 1)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## np.where

In [296]:
A = np.array([0,0,0,1,0])
np.where(A==1) # 조건을 만족하는 인덱스를 반환

(array([3], dtype=int64),)

In [297]:
np.random.seed(43052)
A = np.random.randn(12).reshape(3,4)
np.where(A<0) # 조건을 만족하는 인덱스가 (1,2), (1,3), (2,0), (2,1), (2,3) 이라는 의미

(array([1, 1, 2, 2, 2], dtype=int64), array([2, 3, 0, 1, 3], dtype=int64))

In [298]:
A[np.where(A<0)]

array([-1.66307542, -1.38277318, -1.92684484, -1.4862163 , -0.03488725])

In [308]:
np.where(A<0, 0, A) # 조건이 True이면 0, False이면 A

array([[0.38342049, 1.0841745 , 1.14277825, 0.30789368],
       [0.23778744, 0.35595116, 0.        , 0.        ],
       [0.        , 0.        , 0.00692519, 0.        ]])

In [311]:
np.where(A<0, 5, 1) # 조건이 True이면 0, False이면 1

array([[1, 1, 1, 1],
       [1, 1, 5, 5],
       [5, 5, 1, 5]])

## np.argwhere

In [299]:
A = np.array([0,0,0,1,0])
np.argwhere(A==1)

array([[3]], dtype=int64)

In [300]:
np.random.seed(43052)
A = np.random.randn(12).reshape(3,4)
np.argwhere(A<0) # 조건을 만족하는 인덱스가 (1,2), (1,3), (2,0), (2,1), (2,3) 이라는 의미

array([[1, 2],
       [1, 3],
       [2, 0],
       [2, 1],
       [2, 3]], dtype=int64)

In [301]:
A[np.argwhere(A<0)] # 불가능

IndexError: index 3 is out of bounds for axis 0 with size 3

### Difference between np.where and np.argwhere

`np.where`는 인덱스의 좌표를 읽는 가독성이 떨어지지만 조건에 맞는 원소를 출력하거나 처리하기에 좋다.

`np.argwhere`는 인덱스의 좌표를 읽는 가독성은 좋지만 조건에 맞는 원소를 출력하거나 처리하기에 좋지 못하다.

# Operations

## .sum

In [167]:
A = np.array([1,2,3])
A.sum()

6

## .mean

In [168]:
A = np.array([1,2,3])
A.mean()

2.0

## .min

In [169]:
A = np.array([1,2,3])
A.min()

1

## .max

In [170]:
A = np.array([1,2,3])
A.max()

3

## .prod

In [171]:
A = np.array([1,2,3])
A.prod()

6

## .std

In [178]:
A = np.arange(1,20)
A.std() # 분포를 n으로 나누는 것이 default이다.

5.477225575051661

In [179]:
A = A = np.array([1,2,3])
A.std(ddof=1) # ddof 옵션을 사용하여 분포를 n-1로 나눈다.

1.0

In [180]:
A = A = np.array([1,2,3])
A.std(ddof=2) # ddof 옵션을 사용하여 분포를 n-1로 나눈다.

1.4142135623730951

## .argmin

In [186]:
A = np.array([1,2,3]) # 가장 작은 값의 인덱스를 리턴
A.argmin()

0

In [289]:
np.random.seed(43052)
A = np.random.randn(4*5).reshape(4,5)
A

array([[ 0.38342049,  1.0841745 ,  1.14277825,  0.30789368,  0.23778744],
       [ 0.35595116, -1.66307542, -1.38277318, -1.92684484, -1.4862163 ],
       [ 0.00692519, -0.03488725, -0.34357323,  0.70895648, -1.55100608],
       [ 1.34565583, -0.05654272, -0.83017342, -1.46395159, -0.35459593]])

In [191]:
A.argmin(axis = 0)

array([2, 1, 1, 1, 2], dtype=int64)

In [197]:
A.argmin(axis = 1)

array([4, 3, 4, 3], dtype=int64)

## .argmax

In [198]:
A = np.array([1,2,3]) # 가장 큰 값의 인덱스를 리턴
A.argmax()

2

In [199]:
np.random.seed(43052)
A = np.random.randn(4*5).reshape(4,5)
A

array([[ 0.38342049,  1.0841745 ,  1.14277825,  0.30789368,  0.23778744],
       [ 0.35595116, -1.66307542, -1.38277318, -1.92684484, -1.4862163 ],
       [ 0.00692519, -0.03488725, -0.34357323,  0.70895648, -1.55100608],
       [ 1.34565583, -0.05654272, -0.83017342, -1.46395159, -0.35459593]])

In [200]:
A.argmax(axis = 0)

array([3, 0, 0, 2, 0], dtype=int64)

In [201]:
A.argmax(axis = 1)

array([2, 0, 3, 0], dtype=int64)

## .cumsum

In [207]:
A = np.array([1,2,3,4])
A.cumsum() # 누적합

array([ 1,  3,  6, 10])

## .cumprod

In [212]:
A = np.array([1,2,3,4])
A.cumprod() # 누적곱

array([ 1,  2,  6, 24])

# Applications

## Solving System of Equations

$\begin{cases}
y+z+w = 3 \\ 
x+z+w = 3 \\ 
x+y+w = 3 \\
x+y+z = 3 
\end{cases}$

$\begin{bmatrix} 
0 & 1 & 1 & 1 \\
1 & 0 & 1 & 1 \\
1 & 1 & 0 & 1 \\
1 & 1 & 1 & 0 
\end{bmatrix}
\begin{bmatrix}
x \\ 
y \\ 
z \\ 
w 
\end{bmatrix} =
\begin{bmatrix}
3 \\ 
3 \\ 
3 \\ 
3 
\end{bmatrix}$

$
\begin{bmatrix} 
0 & 1 & 1 & 1 \\
1 & 0 & 1 & 1 \\
1 & 1 & 0 & 1 \\
1 & 1 & 1 & 0 
\end{bmatrix}^{\,-1}
\begin{bmatrix} 
0 & 1 & 1 & 1 \\
1 & 0 & 1 & 1 \\
1 & 1 & 0 & 1 \\
1 & 1 & 1 & 0 
\end{bmatrix}
\begin{bmatrix}
x \\ 
y \\ 
z \\ 
w 
\end{bmatrix} =
\begin{bmatrix} 
0 & 1 & 1 & 1 \\
1 & 0 & 1 & 1 \\
1 & 1 & 0 & 1 \\
1 & 1 & 1 & 0 
\end{bmatrix}^{\,-1}
\begin{bmatrix}
3 \\ 
3 \\ 
3 \\ 
3 
\end{bmatrix}$

$
\begin{bmatrix}
x \\ 
y \\ 
z \\ 
w 
\end{bmatrix} =
\begin{bmatrix} 
0 & 1 & 1 & 1 \\
1 & 0 & 1 & 1 \\
1 & 1 & 0 & 1 \\
1 & 1 & 1 & 0 
\end{bmatrix}^{\,-1}
\begin{bmatrix}
3 \\ 
3 \\ 
3 \\ 
3 
\end{bmatrix}$

In [92]:
v = 'x', 'y', 'z'
A = np.linalg.inv(np.array([[0,1,1,1],[1,0,1,1],[1,1,0,1],[1,1,1,0]]))
B = np.array([3,3,3,3]).reshape(4,1)

answer = A@B.reshape(-1)
for v, i in zip(v, answer): print(v, ':', i)

x : 1.0
y : 1.0
z : 1.0
