# NUMPY HIGHLIGHT

- toc: true
- branch: master
- badges: true
- comments: true
- author: Kim Jeewoo
- categories: [Python]
- image: images/numpy_logo.png

# Reference

ref. https://numpy.org/doc/stable/user/index.html#

# NumPy

- Numerical Python

# import numpy as np

In [1]:
import numpy as np

# Array Creation(ndarray)

- N Dimensional Array

In [7]:
A = np.array([1,2,3])
A

array([1, 2, 3])

In [50]:
mylist = [3, 4, 5]
array_from_list = np.array(mylist)
array_from_list

array([3, 4, 5])

In [51]:
mytuple = (4,5,6)
array_from_tuple = np.array(mytuple)
array_from_tuple

array([4, 5, 6])

In [53]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
np.linspace(0,1,12) # 0 ~ 1을 12등분하여 만듬 (끝점을 포함)

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091, 1.        ])

In [61]:
len(np.linspace(0,1,12))

12

In [66]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [67]:
np.arange(1,6)

array([1, 2, 3, 4, 5])

In [56]:
np.zeros(3) # 0을 3개

array([0., 0., 0.])

In [85]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [57]:
np.ones(3) # 1을 3개

array([1., 1., 1.])

In [86]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [87]:
np.eye(3) # 단위 행렬

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [88]:
np.diag([1,2,3]) # 대각선이 1,2,3인 행렬

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

# Broadcasting and Operation

In [13]:
A+1 # 덧셈

array([2, 3, 4])

In [14]:
A-4 # 뺄셈

array([-3, -2, -1])

In [15]:
A*2 # 곱셈

array([2, 4, 6])

In [16]:
A/2 # 나눗셈

array([0.5, 1. , 1.5])

In [17]:
A**2 # 제곱

array([1, 4, 9])

In [18]:
A%2 # 나머지

array([1, 0, 1], dtype=int32)

In [19]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [20]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [22]:
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [23]:
np.sin(A)

array([0.84147098, 0.90929743, 0.14112001])

In [24]:
A = np.array([11,22,33,44,55,66])

# Indexing

In [27]:
A[2]

33

In [28]:
A[5]

66

In [30]:
A[1:4]

array([22, 33, 44])

In [31]:
A[[0,2,4]]

array([11, 33, 55])

In [33]:
A[[True, False, True, False, False, True]]

array([11, 33, 66])

In [34]:
A < 33

array([ True,  True, False, False, False, False])

In [35]:
A[A<33]

array([11, 22])

## Matrix Indexing

In [38]:
A2 = np.array([[1,2,3,4],[-1,-2,-3,-4],[5,6,7,8],[-5,-6,-7,-8]])
A2

array([[ 1,  2,  3,  4],
       [-1, -2, -3, -4],
       [ 5,  6,  7,  8],
       [-5, -6, -7, -8]])

In [42]:
A2[1][3]

-4

In [43]:
A2[1,3]

-4

In [44]:
A2[0, 0:2]

array([1, 2])

In [48]:
A2[0]

array([1, 2, 3, 4])

In [45]:
A2[0, 2:]

array([3, 4])

In [46]:
A2[:, :]

array([[ 1,  2,  3,  4],
       [-1, -2, -3, -4],
       [ 5,  6,  7,  8],
       [-5, -6, -7, -8]])

In [47]:
A2[[0,2], :]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [49]:
A2[[0,2]]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

# Useful Functions

## reshape

> Tip: R의 `dim`함수와 유사하다.

In [68]:
A = np.array([11,22,33,44,55,66])
A

array([11, 22, 33, 44, 55, 66])

In [69]:
A.reshape(2,3)

array([[11, 22, 33],
       [44, 55, 66]])

In [71]:
A

array([11, 22, 33, 44, 55, 66])

In [73]:
A = A.reshape(2,3)
A

array([[11, 22, 33],
       [44, 55, 66]])

> note : reshape with `-1`

In [74]:
A = np.arange(24)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [82]:
A.reshape(2,-1) # 행의 수가 2인 행렬, 열은 알아서 맞춰

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [81]:
A.reshape(4, -1) # 행의 수가 4인 행렬, 열은 알아서 맞춰

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [80]:
A.reshape(-1, 4) # 열의 수가 4인 행렬, 행은 알아서 맞춰

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [79]:
A.reshape(-1) # 다시 길이가 24인 벡터로

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

## np.random